#define DATA_FOLDER "project data/data/"
#define TRAIN_FOLDER "project data/data/train_images/"
#define TEMPLATE_FOLDER "project data/data/templates/"
#define TEST_FOLDER "project data/data/test_image"
#define RESULT_FOLDER "project data/data/result_image/"
